### ISSUE TITLE
Problem #8 "Writing transfoms" given solution doesnt work, transform only top level module

### ISSUE THREAD

**Issue by raabbajam** [substack/browserify-adventure#20]
Here is the given solution:

./tr.js
``` javascript
var through = require('through2');
var split = require('split');
var sprintf = require('sprintf');
var quote = require('quote-stream');
var combiner = require('stream-combiner');

module.exports = function (file) {
    if (!/\.txt$/.test(file)) return through();
    var num = 0;
    var liner = through(function write (buf, enc, next) {
        var line = buf.toString('utf8') + '\n';
        if (num % 5 === 0) {
            this.push(sprintf('%3d %s', num, line));
        }
        else this.push('    ' + line);
        num ++;
        next();
    });
    var prefix = through();
    prefix.write('module.exports=');
    return combiner(split(), liner, quote(), prefix);
};
```

and here is the main.js

main.js
``` javascript
var txt = require('$NPM_PACKAGES/lib/node_modules/browserify-adventure/problems/writing_transforms/wake.txt');
console.log(txt);
```

command executed  `browserify -t ./tr.js main.js | browserify-adventure verify`

The problem is `browserify -t` will only transform top level module, so this line `var txt = require('$NPM_PACKAGES/lib/node_modules/browserify-adventure/problems/writing_transforms/wake.txt');` will not transformed, resulting in error
```
Be that as it may, but for that light phantastic of his gnose's glow as it
   ^
ParseError: Unexpected token
```

Suggested solution:
After googling stackoverflow I find this link where it specify how to use transform on other module http://stackoverflow.com/questions/16110750/how-to-perform-a-transform-on-npm-module-using-browserify

I haven't succeeded on using the above method. Please advise.

**Comment by morefreeze** [comment]
@raabbajam  do you try cp the `wake.txt` to working directory, and just write `var txt = require('./wake.txt')` in main.js without absolute path ?

**Comment by morefreeze** [comment]
and so you can use `browserify -g ./tr.js main.js`

**Comment by lokken** [comment]
Can confirm that either fix by @morefreeze works. The issue with reading wake.txt when it's located in a node_modules directory is described here: https://github.com/substack/node-browserify/issues/501.

Since the wake.txt file will always be downloaded into a node_modules directory when you install browserify-adventure, I think updating the text of the lesson to tell us to copy the file or use -g would be nice.

**Comment by kgraves** [comment]
I'm also having this issue and have __not__ been able to resolve it with @morefreeze's advice.

I first tried using the official solution [here](https://github.com/substack/browserify-adventure/tree/master/solutions/writing_transforms) and got the following output:
```bash
$ browserify -t ./tr.js main.js | browserify-adventure verify

TAP version 13

/home/kg/.nvm/versions/node/v5.0.0/lib/node_modules/browserify-adventure/problems/writing_transforms/wake.txt:1
Be that as it may, but for that light phantastic of his gnose's glow as it
   ^
ParseError: Unexpected token
# (anonymous)
not ok 1 The input is not a browserify bundle!
  ---
    operator: fail
    at: ConcatStream.<anonymous> (/home/kg/.nvm/versions/node/v5.0.0/lib/node_modules/browserify-adventure/node_modules/concat-stream/index.js:36:43)
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################


  ...

```

I also tried using the above mentioned solution, but that yields a different error:
```bash
$ browserify -g ./tr.js main.js | browserify-adventure verify

TAP version 13
# (anonymous)
not ok 1 The input is not a browserify bundle!
  ---
    operator: fail
    at: ConcatStream.<anonymous> (/home/kg/.nvm/versions/node/v5.0.0/lib/node_modules/browserify-adventure/node_modules/concat-stream/index.js:36:43)
#########################################
###   YOUR SOLUTION IS NOT CORRECT!   ###
#########################################


  ...

```

Any advice on this one? I'm going to start debugging, but was hoping someone out there has already figured this out.

**Comment by robooo** [comment]
i have same error as @kgraves but with this path(on mac) 
```
operator: fail
    at: ConcatStream.<anonymous> (/usr/local/lib/node_modules/browserify-adventure/node_modules/concat-stream/index.js:36:43)
```
