### ISSUE TITLE
Issue with running writing-transforms solution

### ISSUE THREAD

**Issue by mchirlin** [substack/browserify-adventure#25]
I have run the provided solution directly out of the box and the output of browserify -t ./tr.js main.js is blank.  When I remove `split()` from the list of transforms then the result at least has a value, but is just one row prepended with a `  0 `.  When I put in console.logging inside of the liner function I see that split seems to have work and it outputs on the interface correctly. But when running it all together I get nothing.  Am I missing anything obvious? Or maybe this is a version issue.

**main.js**
```
var txt = require('./wake.txt');
console.log(txt);
```

**tr.js**
```
var through = require('through2');
var split = require('split');
var sprintf = require('sprintf');
var quote = require('quote-stream');
var combine = require('stream-combiner2');

module.exports = function (file) {
  if (!/\.txt$/.test(file)) return through();
  var num = 0;
  var liner = through(function write (buf, enc, next) {
    var line = buf.toString('utf8') + '\n';
    if (num % 5 === 0) {
      // Add a line number and push to stream
      this.push(sprintf('%3d %s', num, line));
    } else {
      // Add p and push to stream
      this.push('    ' + line);
    }
    num++;

    // Process next batch
    next();
  });

  // Add 'module.exports=' so this will be considered an exportable module
  var prefix = through();
  prefix.push('module.exports=');

  // Return a through function
  // in this case it is a combination of multiple transformers
  return combine([
    split(),
    liner,
    quote(),
    prefix
  ]);
};
```

**package.json**
```
{
  "name": "browserify-adventure",
  "version": "1.0.0",
  "description": "",
  "main": "beep-boop.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "domify": "^1.4.0",
    "querystring": "^0.2.0",
    "quote-stream": "^1.0.2",
    "split": "^1.0.0",
    "sprintf": "^0.1.5",
    "stream-combiner2": "^1.1.1",
    "through2": "^2.0.1",
    "uniq": "^1.0.1"
  }
}
```

**Comment by mchirlin** [comment]
I've run it using the versions from the package.json file in the browserify-adventure folder and still no dice.  

Running on Windows if that is relevant.

**Comment by noffle** [comment]
I took a look: this doesn't seem to be anything incorrect you've done. I think there's an issue with `split` and how it's getting upgraded to streams3. There are a bunch of workarounds:

1. put an empty `through()` at the front of your combiner pipeline
2. use [`split2`](https://github.com/mcollina/split2) instead of `split`
3. use [`pumpify`](https://github.com/mafintosh/pumpify) instead of `stream-combiner2`

I'll dig a little deeper and see if I can find a nice fix, so that others don't hit this roadbump too. Thanks for reporting!

**Comment by mchirlin** [comment]
Thanks, I used split2 and that resolved the issue.
